#Here we can loop over the coordinates of the plastic disk/Na22 source
#In the real experiment, radial distance was fixed, the plate rotated of 2.5 deg steps
#
#/control/loop scandet.mac rhoDisk 10 100 10
#/control/loop scandet.mac rhoSource 10 100 10

#/run/initialize
/control/loop scandet.mac alphadisk 225.0 585.0 2.5
/control/loop scandet.mac alphasource 225.0 585.0 2.5
#/control/loop scandet.mac alpha 10. 100. 10.
